import { useEffect, useMemo, useState, type ButtonHTMLAttributes, type ReactNode } from 'react'
import { sampleExercises } from './data/sampleContent'

type Screen = 'home' | 'workout' | 'progress' | 'library' | 'settings'
type IconName = 'home' | 'bolt' | 'chart' | 'book' | 'settings' | 'arrow' | 'sun' | 'moon' | 'check' | 'play' | 'chevron' | 'more' | 'clock' | 'weight' | 'calendar'

const nav: { id: Screen; label: string; icon: IconName }[] = [
  { id: 'home', label: 'Home', icon: 'home' }, { id: 'workout', label: 'Workout', icon: 'bolt' }, { id: 'progress', label: 'Progress', icon: 'chart' }, { id: 'library', label: 'Library', icon: 'book' }, { id: 'settings', label: 'Settings', icon: 'settings' },
]

function Icon({ name, size = 22 }: { name: IconName; size?: number }) {
  const d: Record<IconName, ReactNode> = {
    home: <><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z" /></>,
    bolt: <path d="m13 2-9 12h7l-1 8 10-13h-7V2Z" />, chart: <><path d="M4 20V10m6 10V4m6 16v-7m4 7H2" /></>,
    book: <><path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v17H6.5A2.5 2.5 0 0 0 4 21.5v-17Z" /><path d="M4 19a2.5 2.5 0 0 1 2.5-2.5H20" /></>,
    settings: <><circle cx="12" cy="12" r="3" /><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.06 2.06-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56v.09h-2.92v-.09a1.7 1.7 0 0 0-1.03-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-2.06-2.06.06-.06A1.7 1.7 0 0 0 7.22 15a1.7 1.7 0 0 0-1.56-1.03h-.09v-2.92h.09A1.7 1.7 0 0 0 7.22 10a1.7 1.7 0 0 0-.34-1.88l-.06-.06L8.88 6l.06.06A1.7 1.7 0 0 0 10.82 6a1.7 1.7 0 0 0 1.03-1.56v-.09h2.92v.09A1.7 1.7 0 0 0 15.8 6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.06 2.06-.06.06A1.7 1.7 0 0 0 19.4 10a1.7 1.7 0 0 0 1.56 1.03h.09v2.92h-.09A1.7 1.7 0 0 0 19.4 15Z" /></>,
    arrow: <path d="M5 12h14m-6-6 6 6-6 6" />, sun: <><circle cx="12" cy="12" r="4" /><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4m11.4-11.4 1.4-1.4" /></>, moon: <path d="M20 15.4A8.5 8.5 0 0 1 8.6 4 8.5 8.5 0 1 0 20 15.4Z" />,
    check: <path d="m5 12 4.2 4.2L19.5 6" />, play: <path d="m9 6 9 6-9 6V6Z" />, chevron: <path d="m9 18 6-6-6-6" />, more: <><circle cx="5" cy="12" r="1" fill="currentColor" /><circle cx="12" cy="12" r="1" fill="currentColor" /><circle cx="19" cy="12" r="1" fill="currentColor" /></>,
    clock: <><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3.5 2" /></>, weight: <><path d="M6 9V6m12 3V6M4 8h16v8H4zM2 10v4m20-4v4" /></>, calendar: <><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M7 3v4m10-4v4M3 10h18" /></>,
  }
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{d[name]}</svg>
}

function Button({ variant = 'primary', children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' }) {
  return <button className={`button ${variant}`} {...props}>{children}</button>
}

function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section> }
function SectionHead({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="section-head"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{action}</div> }

function App() {
  const [screen, setScreen] = useState<Screen>('home')
  const [theme, setTheme] = useState<'light' | 'dark'>('dark')
  const [toast, setToast] = useState<string | null>(null)
  useEffect(() => { document.documentElement.dataset.theme = theme }, [theme])
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 2800); return () => window.clearTimeout(timer) }, [toast])
  const notify = (message: string) => setToast(message)
  const content = useMemo(() => {
    const props = { changeScreen: setScreen, notify }
    if (screen === 'home') return <Home {...props} />
    if (screen === 'workout') return <Workout notify={notify} />
    if (screen === 'progress') return <Progress />
    if (screen === 'library') return <Library notify={notify} />
    return <Settings theme={theme} setTheme={setTheme} notify={notify} />
  }, [screen, theme])
  return <div className="app-shell"><header className="topbar"><button className="wordmark" onClick={() => setScreen('home')} aria-label="Forge home"><span>F</span>FORGE</button><button className="profile-avatar" aria-label="Open profile" onClick={() => notify('Profile setup arrives in Milestone 2')}>AJ</button></header><main className="page">{content}</main><nav className="bottom-nav" aria-label="Primary navigation">{nav.map((item) => <button key={item.id} className={screen === item.id ? 'active' : ''} onClick={() => setScreen(item.id)} aria-current={screen === item.id ? 'page' : undefined}><Icon name={item.icon} size={20} /><span>{item.label}</span></button>)}</nav>{toast && <div className="toast" role="status"><Icon name="check" size={18} />{toast}</div>}</div>
}

function Home({ changeScreen, notify }: { changeScreen: (screen: Screen) => void; notify: (message: string) => void }) {
  return <div className="stack"><section className="intro"><p className="eyebrow">TUESDAY · SEPTEMBER 2</p><h1>Good morning, Alex.</h1><p>Small, steady work builds strength that lasts.</p></section><Card className="hero-card"><div className="hero-top"><div className="session-icon"><Icon name="bolt" /></div><span className="pill">TODAY</span></div><p className="eyebrow">YOUR PLAN</p><h2>Foundation Strength</h2><p className="muted">A focused session shaped around your preferences.</p><div className="session-meta"><span><Icon name="clock" size={17} /> About 45 min</span><span><Icon name="calendar" size={17} /> 5 movements</span></div><Button onClick={() => changeScreen('workout')}>Preview workout <Icon name="arrow" size={18} /></Button></Card><section><SectionHead eyebrow="THIS WEEK" title="Your rhythm" action={<button className="text-button" onClick={() => changeScreen('progress')}>View progress</button>} /><Card className="week-card"><div className="week-days">{['M','T','W','T','F','S','S'].map((day, i) => <div key={`${day}-${i}`} className={`day ${i === 1 ? 'today' : ''} ${i === 0 ? 'done' : ''}`}><span>{day}</span><i>{i === 0 ? <Icon name="check" size={13} /> : i === 1 ? '•' : ''}</i></div>)}</div><div className="week-detail"><strong>1 of 3 sessions</strong><span>Keep the momentum going.</span></div></Card></section><section className="stats-grid"><Stat label="Current weight" value="—" note="Add your first check-in" icon="weight" /><Stat label="Last session" value="—" note="Your history will show here" icon="clock" /></section><Card className="gentle-card"><div className="mini-icon"><Icon name="sun" size={20} /></div><div><strong>Start with what feels right</strong><p>Forge will use your plan and your feedback—never a guessed weight.</p></div><button aria-label="Learn more" onClick={() => notify('Safety guidance arrives with onboarding')}><Icon name="chevron" size={20} /></button></Card></div>
}

function Workout({ notify }: { notify: (message: string) => void }) { return <div className="stack"><section className="intro"><p className="eyebrow">WORKOUT</p><h1>Today’s session</h1><p>Review your plan before you start. Nothing begins until you’re ready.</p></section><Card className="workout-preview"><div className="preview-header"><div><span className="pill soft">FOUNDATION</span><h2>Full body strength</h2></div><button className="circle-button" aria-label="More options" onClick={() => notify('Plan options will be available after import')}><Icon name="more" /></button></div><div className="workout-stat-row"><span><Icon name="clock" />45 min</span><span><Icon name="bolt" />5 movements</span><span><Icon name="calendar" />Beginner friendly</span></div><div className="exercise-list">{['Warm up', 'Primary movement', 'Pull movement', 'Lower body', 'Finisher'].map((item, index) => <div className="exercise-row" key={item}><span className="exercise-number">0{index + 1}</span><div><strong>{item}</strong><p>{index === 0 ? 'Move gently and check in with your body' : 'Details come from your imported plan'}</p></div><Icon name="chevron" size={19} /></div>)}</div></Card><Card className="readiness-card"><div><p className="eyebrow">BEFORE YOU BEGIN</p><h3>How much time do you have?</h3><p>We’ll preserve your plan’s priorities when time is limited.</p></div><div className="time-options"><button className="selected">45 min</button><button onClick={() => notify('Time-aware plan compression is planned for Milestone 4')}>30 min</button><button onClick={() => notify('Time-aware plan compression is planned for Milestone 4')}>60 min</button></div></Card><Button disabled aria-disabled="true">Start session in Milestone 4 <Icon name="arrow" size={18} /></Button><p className="feature-note">Workout execution is intentionally not active yet. This protects plan logic until the generic engine is ready.</p></div> }

function Progress() { return <div className="stack"><section className="intro"><p className="eyebrow">PROGRESS</p><h1>Your progress,<br />at a glance.</h1><p>Track patterns, not perfect days.</p></section><Card className="progress-hero"><div><p className="eyebrow">WEEKLY CONSISTENCY</p><h2>Ready to begin</h2><p>Your completed sessions and check-ins will build a clear picture here.</p></div><div className="progress-ring"><span>0</span><small>/ 3</small></div></Card><section><SectionHead title="Progress spaces" /><div className="progress-list"><ProgressItem icon="weight" title="Body weight" text="Log your first check-in to see your trend." /><ProgressItem icon="bolt" title="Strength" text="Completed sessions will create your exercise history." /><ProgressItem icon="chart" title="Training rhythm" text="Your weekly consistency will appear here." /></div></section><Card className="empty-card"><div className="empty-mark"><Icon name="chart" size={25} /></div><h3>Progress that stays human</h3><p>We’ll show meaningful trends once you have enough history—not noisy day-to-day fluctuations.</p></Card></div> }

function Library({ notify }: { notify: (message: string) => void }) { const [query, setQuery] = useState(''); const exercises = sampleExercises.filter((e) => e.displayName.toLowerCase().includes(query.toLowerCase()) || e.primaryMuscles.join(' ').toLowerCase().includes(query.toLowerCase())); return <div className="stack"><section className="intro"><p className="eyebrow">EXERCISE LIBRARY</p><h1>Learn with confidence.</h1><p>Clear setup, calm cues, and movement guidance.</p></section><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search movements or muscles" /></label><div className="filter-row"><button className="filter-active">All movements</button><button>Machines</button><button>Dumbbells</button><button>Bodyweight</button></div><section><SectionHead title={`${exercises.length} starter movements`} /><div className="library-grid">{exercises.map((exercise, index) => <article className="exercise-tile" key={exercise.id}><div className={`exercise-visual visual-${index}`}><span>{exercise.primaryMuscles[0]}</span><button aria-label={`Preview ${exercise.displayName}`} onClick={() => notify('Exercise detail pages arrive in Milestone 3')}><Icon name="play" size={17} /></button></div><div><span className="tag">BEGINNER</span><h3>{exercise.displayName}</h3><p>{exercise.primaryMuscles.join(' · ')}</p></div></article>)}</div>{exercises.length === 0 && <Card className="empty-card"><div className="empty-mark">⌕</div><h3>No matches yet</h3><p>Try a muscle group or a simpler search.</p></Card>}</section><Card className="library-note"><Icon name="book" size={21} /><p>Your future plan imports will reference this library, instead of burying exercise instructions in the workout screen.</p></Card></div> }

function Settings({ theme, setTheme, notify }: { theme: 'light' | 'dark'; setTheme: (theme: 'light' | 'dark') => void; notify: (message: string) => void }) { return <div className="stack"><section className="intro"><p className="eyebrow">SETTINGS</p><h1>Make Forge yours.</h1><p>Personal details, preferences, and plan management live here.</p></section><section><SectionHead title="Appearance" /><Card className="settings-card"><div className="setting-row"><div className="setting-icon"><Icon name={theme === 'dark' ? 'moon' : 'sun'} /></div><div><strong>Theme</strong><p>Choose what feels best in your gym.</p></div><div className="theme-switch" role="group" aria-label="Theme"><button className={theme === 'light' ? 'selected' : ''} onClick={() => setTheme('light')} aria-label="Light theme"><Icon name="sun" size={17} /></button><button className={theme === 'dark' ? 'selected' : ''} onClick={() => setTheme('dark')} aria-label="Dark theme"><Icon name="moon" size={17} /></button></div></div></Card></section><section><SectionHead title="Your foundation" /><Card className="settings-card links"><SettingsLink icon="home" title="Profile & goals" subtitle="Goal, experience, schedule" action={() => notify('Profile onboarding is Milestone 2')} /><SettingsLink icon="calendar" title="Workout plan" subtitle="Import or replace your plan" action={() => notify('Structured plan import is Milestone 2')} /><SettingsLink icon="book" title="Equipment" subtitle="Your available gym setup" action={() => notify('Equipment setup is Milestone 2')} /></Card></section><section><SectionHead title="App" /><Card className="settings-card links"><SettingsLink icon="bolt" title="Voice & accessibility" subtitle="Designed to stay clear and calm" action={() => notify('Accessibility controls are coming soon')} /><SettingsLink icon="settings" title="About Forge" subtitle="Local-first personal gym coach" action={() => notify('Forge Milestone 1 · Local shell')} /></Card></section><p className="privacy-note">Your future profile, plan, and workout history will remain on this device until you choose otherwise.</p></div> }

function Stat({ label, value, note, icon }: { label: string; value: string; note: string; icon: IconName }) { return <Card className="stat-card"><div className="stat-icon"><Icon name={icon} size={19} /></div><p>{label}</p><h3>{value}</h3><span>{note}</span></Card> }
function ProgressItem({ icon, title, text }: { icon: IconName; title: string; text: string }) { return <Card className="progress-item"><div className="mini-icon"><Icon name={icon} size={20} /></div><div><h3>{title}</h3><p>{text}</p></div><Icon name="chevron" size={19} /></Card> }
function SettingsLink({ icon, title, subtitle, action }: { icon: IconName; title: string; subtitle: string; action: () => void }) { return <button className="settings-link" onClick={action}><div className="setting-icon"><Icon name={icon} /></div><div><strong>{title}</strong><p>{subtitle}</p></div><Icon name="chevron" size={19} /></button> }

export default App
