import { useEffect, useState, type ReactNode } from 'react'
import { Onboarding } from './components/Onboarding'
import { sampleExercises } from './data/sampleContent'
import { equipmentCatalog } from './data/equipment'
import type { LocalAppData, UserProfile } from './domain/types'
import { useLocalAppData } from './hooks/useLocalAppData'
import { useAppNavigation, type Screen } from './hooks/useAppNavigation'
import { parseChatGptPlan } from './engine/planImport'
import { resolveToday } from './engine/workoutEngine'

type IconName = 'home' | 'bolt' | 'chart' | 'book' | 'settings' | 'arrow' | 'sun' | 'moon' | 'check' | 'play' | 'chevron' | 'clock' | 'weight' | 'calendar'
const nav: { id: Screen; label: string; icon: IconName }[] = [{ id: 'home', label: 'Home', icon: 'home' }, { id: 'workout', label: 'Workout', icon: 'bolt' }, { id: 'progress', label: 'Progress', icon: 'chart' }, { id: 'library', label: 'Library', icon: 'book' }, { id: 'settings', label: 'Settings', icon: 'settings' }]

function Icon({ name, size = 22 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, ReactNode> = { home: <path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z" />, bolt: <path d="m13 2-9 12h7l-1 8 10-13h-7V2Z" />, chart: <path d="M4 20V10m6 10V4m6 16v-7m4 7H2" />, book: <><path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v17H6.5A2.5 2.5 0 0 0 4 21.5v-17Z" /><path d="M4 19a2.5 2.5 0 0 1 2.5-2.5H20" /></>, settings: <><circle cx="12" cy="12" r="3" /><path d="M12 2v3m0 14v3M2 12h3m14 0h3M4.9 4.9 7 7m10 10 2.1 2.1M19.1 4.9 17 7M7 17l-2.1 2.1" /></>, arrow: <path d="M5 12h14m-6-6 6 6-6 6" />, sun: <><circle cx="12" cy="12" r="4" /><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2" /></>, moon: <path d="M20 15.4A8.5 8.5 0 0 1 8.6 4 8.5 8.5 0 1 0 20 15.4Z" />, check: <path d="m5 12 4.2 4.2L19.5 6" />, play: <path d="m9 6 9 6-9 6V6Z" />, chevron: <path d="m9 18 6-6-6-6" />, clock: <><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3.5 2" /></>, weight: <path d="M6 9V6m12 3V6M4 8h16v8H4zM2 10v4m20-4v4" />, calendar: <><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M7 3v4m10-4v4M3 10h18" /></> }
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}
function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section> }
function Button({ children, disabled, onClick }: { children: ReactNode; disabled?: boolean; onClick?: () => void }) { return <button className="button primary" disabled={disabled} onClick={onClick}>{children}</button> }
function Head({ eyebrow, title }: { eyebrow?: string; title: string }) { return <section className="intro">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1></section> }

export default function App() {
  const { screen, selectedExerciseId, workoutStarted, setScreen, selectExercise, setWorkoutStarted, goBack, resetRoot } = useAppNavigation('home')
  const [toast, setToast] = useState<string | null>(null); const { data, status, update } = useLocalAppData(); const theme = data?.appSettings.theme === 'light' ? 'light' : 'dark'
  useEffect(() => { document.documentElement.dataset.theme = theme }, [theme]); useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 2600); return () => window.clearTimeout(timer) }, [toast])
  if (status === 'loading') return <Launch text="Preparing your local workspace…" />
  if (status === 'unavailable') return <Launch text="Local storage is unavailable. Enable browser storage for Forge, then reload." error />
  if (!data) return <Onboarding onComplete={(next) => { update(next); resetRoot('home') }} />
  const notify = (message: string) => setToast(message)
  const setTheme = (next: 'light' | 'dark') => update({ ...data, appSettings: { ...data.appSettings, theme: next } })
  const content = screen === 'home'
    ? <Home profile={data.profile} onWorkout={() => setScreen('workout')} />
    : screen === 'workout'
    ? <Workout data={data} update={update} notify={notify} started={workoutStarted} onStart={() => setWorkoutStarted(true)} onExit={() => goBack(() => setWorkoutStarted(false))} />
    : screen === 'progress'
    ? <Progress />
    : screen === 'library'
    ? <Library notify={notify} selectedId={selectedExerciseId} onSelect={(id) => selectExercise(id)} onBack={() => goBack(() => selectExercise(null))} />
    : <Settings data={data} update={update} theme={theme} setTheme={setTheme} notify={notify} />
  return <div className="app-shell"><header className="topbar"><button className="wordmark" onClick={() => setScreen('home')} aria-label="Forge home"><span>F</span>FORGE</button><button className="profile-avatar" onClick={() => setScreen('settings')} aria-label="Open settings">{data.profile.displayName.slice(0, 2).toUpperCase()}</button></header><main className="page">{content}</main><nav className="bottom-nav" aria-label="Primary navigation">{nav.map((item) => <button key={item.id} className={screen === item.id ? 'active' : ''} onClick={() => setScreen(item.id)} aria-current={screen === item.id ? 'page' : undefined}><Icon name={item.icon} size={20} /><span>{item.label}</span></button>)}</nav>{toast && <div className="toast" role="status"><Icon name="check" size={18} />{toast}</div>}</div>
}

function Launch({ text, error }: { text: string; error?: boolean }) { return <main className="launch-state"><div className="wordmark"><span>F</span>FORGE</div>{!error && <div className="launch-pulse" />}<h1>{error ? 'Your data stays local.' : 'Setting up Forge'}</h1><p>{text}</p></main> }
function Home({ profile, onWorkout }: { profile: UserProfile; onWorkout: () => void }) { return <div className="stack"><Head eyebrow="YOUR LOCAL WORKSPACE" title={`Good morning, ${profile.displayName}.`} /><p className="home-lede">Small, steady work builds strength that lasts.</p><Card className="hero-card"><div className="hero-top"><div className="session-icon"><Icon name="bolt" /></div><span className="pill">PROFILE READY</span></div><p className="eyebrow">YOUR PLAN FOUNDATION</p><h2>Ready for your plan</h2><p className="muted">Your preferences are saved locally. A future plan import will provide the workout details.</p><div className="session-meta"><span><Icon name="clock" size={17} /> {profile.preferredDurationMinutes} min preference</span><span><Icon name="calendar" size={17} /> {profile.availableDays.length} training days</span></div><Button onClick={onWorkout}>View workout space <Icon name="arrow" size={18} /></Button></Card><section><div className="section-head"><div><p className="eyebrow">THIS WEEK</p><h2>Your rhythm</h2></div></div><Card className="week-card"><div className="week-days">{['M','T','W','T','F','S','S'].map((day, index) => { const dayNo = (index + 1) % 7; return <div key={`${day}-${index}`} className={`day ${profile.availableDays.includes(dayNo) ? 'today' : ''}`}><span>{day}</span><i>{profile.availableDays.includes(dayNo) ? '•' : ''}</i></div> })}</div><div className="week-detail"><strong>{profile.availableDays.length} preferred sessions</strong><span>Your plan will fill in the details.</span></div></Card></section><section className="stats-grid"><Stat label="Current weight" value="—" note="Add a check-in later" icon="weight" /><Stat label="Workout history" value="—" note="No sessions yet" icon="clock" /></section></div> }
function Workout({ data, update, notify, started, onStart, onExit }: { data: LocalAppData; update: (next: LocalAppData) => void; notify: (message: string) => void; started: boolean; onStart: () => void; onExit: () => void }) { const [raw,setRaw]=useState(''); const [errors,setErrors]=useState<string[]>([]); const activePlan=data.plans.find(p=>p.id===data.activePlanId); const today=activePlan?resolveToday(activePlan,data.inventory):null; const importPlan=()=>{const parsed=parseChatGptPlan(raw);if(!parsed.ok){setErrors(parsed.errors);return}const now=new Date().toISOString();const plan={...parsed.plan,id:crypto.randomUUID(),profileId:data.profile.id,version:1,status:'active' as const,source:'chatgpt_import' as const,createdAt:now};update({...data,plans:[...data.plans.map(i=>({...i,status:'archived' as const})),plan],activePlanId:plan.id});setRaw('');notify('Plan imported locally.')}; if(started&&today?.kind==='workout') return <ActiveWorkout exercises={today.exercises??[]} onExit={onExit} />; return <div className="stack"><Head eyebrow="WORKOUT" title="Your workout space" />{activePlan&&today?<><Card className="workout-preview"><p className="eyebrow">TODAY’S PLAN</p><h2>{today.title??'Recovery day'}</h2><p className="muted">{today.message}</p>{today.kind==='workout'&&<Button onClick={onStart}>Start today’s workout <Icon name="arrow" size={18}/></Button>}</Card></>:<Card className="readiness-card"><p className="eyebrow">IMPORT STRUCTURED PLAN</p><textarea className="plan-input" value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'{"title":"My plan","schedule":[],"workoutDays":[]}'}/><Button onClick={importPlan}>Validate & import plan</Button>{errors.map(e=><p className="import-errors" key={e}>{e}</p>)}</Card>}</div> }
function ActiveWorkout({ exercises,onExit }:{exercises:{exerciseId:string;unavailable:boolean}[];onExit:()=>void}){const [index,setIndex]=useState(0),[sets,setSets]=useState(0),[weight,setWeight]=useState(''),[reps,setReps]=useState(''),[seconds,setSeconds]=useState(0);useEffect(()=>{const id=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>window.clearInterval(id)},[]);const current=exercises[index];return <main className="active-workout"><button className="back-button" onClick={onExit}>Exit workout</button><p className="eyebrow">ACTIVE WORKOUT · {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</p><h1>{current.exerciseId.replaceAll('-',' ')}</h1><p>Set {sets+1} · start light and choose your own safe weight.</p><div className="set-fields"><label>Weight<input inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value)} placeholder="kg"/></label><label>Reps<input inputMode="numeric" value={reps} onChange={e=>setReps(e.target.value)} placeholder="reps"/></label></div><div className="rir"><span>Good reps left</span>{['0','1','2','3+'].map(r=><button key={r}>{r}</button>)}</div><Button disabled={!weight||!reps} onClick={()=>{setSets(s=>s+1);setReps('')}}>Complete set</Button>{sets>=2&&<Button onClick={()=>{if(index<exercises.length-1){setIndex(i=>i+1);setSets(0);setWeight('')}else onExit()}}>Next exercise <Icon name="arrow" size={18}/></Button>}<p className="feature-note">Rest and equipment-wait controls arrive in the next milestone.</p></main>}
function Progress() { return <div className="stack"><Head eyebrow="PROGRESS" title="Your progress, at a glance." /><p className="home-lede">Track patterns, not perfect days.</p><Card className="progress-hero"><div><p className="eyebrow">WEEKLY CONSISTENCY</p><h2>Ready to begin</h2><p>Your completed sessions and check-ins will build a clear picture here.</p></div><div className="progress-ring"><span>0</span><small>/ 0</small></div></Card><Card className="empty-card"><div className="empty-mark"><Icon name="chart" size={25} /></div><h3>Progress that stays human</h3><p>We’ll show useful trends only after there is enough history.</p></Card></div> }
function Library({ notify, selectedId, onSelect, onBack }: { notify: (message: string) => void; selectedId: string | null; onSelect: (id: string) => void; onBack: () => void }) {
  const [query, setQuery] = useState(''); const selected = sampleExercises.find((exercise) => exercise.id === selectedId); const results = sampleExercises.filter((exercise) => exercise.displayName.toLowerCase().includes(query.toLowerCase()) || [...exercise.primaryMuscles, ...exercise.secondaryMuscles].join(' ').toLowerCase().includes(query.toLowerCase()))
  if (selected) return <ExerciseDetail exercise={selected} back={onBack} notify={notify} />
  return <div className="stack"><Head eyebrow="EXERCISE LIBRARY" title="Learn with confidence." /><p className="home-lede">Clear setup, calm cues, and substitutions for a real gym.</p><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search movements or muscles" /></label><section><div className="section-head"><div><p className="eyebrow">CURATED FOR BEGINNERS</p><h2>{results.length} movements</h2></div></div><div className="library-grid">{results.map((exercise, index) => <button className="exercise-tile library-button" key={exercise.id} onClick={() => onSelect(exercise.id)}><div className={`exercise-visual visual-${index % 4}`}><span>{exercise.primaryMuscles[0]}</span><i>{exercise.mediaType === 'youtube' ? <Icon name="play" size={17} /> : '→'}</i></div><span className="tag">BEGINNER</span><h3>{exercise.displayName}</h3><p>{exercise.primaryMuscles.join(' · ')}</p></button>)}</div>{results.length === 0 && <Card className="empty-card"><div className="empty-mark">⌕</div><h3>No matches yet</h3><p>Try a muscle group or a shorter search.</p></Card>}</section><Card className="library-note"><Icon name="book" size={21} /><p>Every movement includes text guidance, so a missing or offline video never leaves you without a safe next step.</p></Card></div>
}
function ExerciseDetail({ exercise, back, notify }: { exercise: typeof sampleExercises[number]; back: () => void; notify: (message: string) => void }) {
  const video = exercise.videos[0]
  return <div className="stack exercise-detail"><button className="back-button detail-back" onClick={back}>‹ Back to library</button><section className="detail-title"><p className="eyebrow">{exercise.movementPattern.replace('_', ' ')}</p><h1>{exercise.displayName}</h1><p>{exercise.primaryMuscles.join(' · ')} <span>·</span> {exercise.equipmentRequired.map((id) => id.replaceAll('-', ' ')).join(', ')}</p></section><div className="detail-visual"><span>{exercise.primaryMuscles[0]}</span>{video ? <button onClick={() => window.open(video.url, '_blank', 'noopener,noreferrer')}><Icon name="play" size={19} /> Watch curated demo</button> : <div><Icon name="book" size={19} /> Text guidance available</div>}</div>{video ? <Card className="video-card"><div><p className="eyebrow">CURATED VIDEO</p><strong>{video.title}</strong><p>{video.creator} · YouTube</p></div><button className="text-button" onClick={() => window.open(video.url, '_blank', 'noopener,noreferrer')}>Open demo</button></Card> : <Card className="video-card"><div><p className="eyebrow">VIDEO UNAVAILABLE</p><strong>Use the written steps below</strong><p>Video is optional; the safety and setup notes remain available offline.</p></div></Card>}<DetailList title="Set up" items={exercise.setupInstructions} /><DetailList title="Move with control" items={exercise.instructions} /><Card className="cue-card"><p className="eyebrow">BREATHING CUE</p><strong>{exercise.breathingCue}</strong>{exercise.tempoCue && <p>{exercise.tempoCue}</p>}</Card><DetailList title="Keep an eye on" items={exercise.commonMistakes} tone="mistakes" /><Card className="safety-card"><p className="eyebrow">SAFETY NOTE</p>{exercise.safetyNotes.map((note) => <p key={note}>{note}</p>)}</Card><section><div className="section-head"><div><p className="eyebrow">IF EQUIPMENT IS BUSY</p><h2>Alternatives</h2></div></div><div className="substitution-list">{exercise.substitutions.map((substitution) => { const alternative = sampleExercises.find((item) => item.id === substitution.exerciseId); return <button key={substitution.exerciseId} onClick={() => notify(`${alternative?.displayName ?? 'Alternative'} is a ranked substitute for a future workout engine.`)}><div><strong>{alternative?.displayName ?? substitution.exerciseId}</strong><p>{substitution.reason}</p></div><span>{Math.round(substitution.score * 100)}%</span></button> })}</div></section></div>
}
function DetailList({ title, items, tone }: { title: string; items: string[]; tone?: 'mistakes' }) { return <section className={tone ? 'detail-list attention-list' : 'detail-list'}><div className="section-head"><h2>{title}</h2></div><ol>{items.map((item) => <li key={item}>{item}</li>)}</ol></section> }
function Settings({ data, update, theme, setTheme, notify }: { data: LocalAppData; update: (next: LocalAppData) => void; theme: 'light' | 'dark'; setTheme: (next: 'light' | 'dark') => void; notify: (message: string) => void }) {
  const [equipmentOpen, setEquipmentOpen] = useState(false); const [name, setName] = useState(data.profile.displayName)
  const saveName = () => { const displayName = name.trim(); if (!displayName) return; update({ ...data, profile: { ...data.profile, displayName, updatedAt: new Date().toISOString() } }); notify('Profile saved locally.') }
  const toggleEquipment = (id: string) => { const current = data.inventory.availableEquipmentIds; const availableEquipmentIds = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; update({ ...data, inventory: { ...data.inventory, availableEquipmentIds, updatedAt: new Date().toISOString() } }) }
  return <div className="stack"><Head eyebrow="SETTINGS" title="Make Forge yours." /><section><div className="section-head"><h2>Profile</h2></div><Card className="settings-card profile-edit"><label className="name-field"><span>Your name</span><input value={name} onChange={(event) => setName(event.target.value)} maxLength={32} /></label><Button onClick={saveName}>Save profile</Button><p className="profile-summary">{data.profile.experience} · {data.profile.availableDays.length} training days · {data.profile.preferredDurationMinutes} min</p></Card></section><section><div className="section-head"><h2>Appearance</h2></div><Card className="settings-card"><div className="setting-row"><div className="setting-icon"><Icon name={theme === 'dark' ? 'moon' : 'sun'} /></div><div><strong>Theme</strong><p>Saved on this device.</p></div><div className="theme-switch"><button className={theme === 'light' ? 'selected' : ''} onClick={() => setTheme('light')} aria-label="Light theme"><Icon name="sun" size={17} /></button><button className={theme === 'dark' ? 'selected' : ''} onClick={() => setTheme('dark')} aria-label="Dark theme"><Icon name="moon" size={17} /></button></div></div></Card></section><section><div className="section-head"><h2>Equipment inventory</h2><button className="text-button" onClick={() => setEquipmentOpen(!equipmentOpen)}>{equipmentOpen ? 'Done' : 'Edit'}</button></div><Card className="settings-card"><div className="inventory-summary"><strong>{data.inventory.availableEquipmentIds.length} items available</strong><p>Only compatible movements may be chosen by the future workout engine.</p></div>{equipmentOpen && <div className="settings-equipment">{equipmentCatalog.map((item) => { const checked = data.inventory.availableEquipmentIds.includes(item.id); return <label className="check-row" key={item.id}><input type="checkbox" checked={checked} onChange={() => toggleEquipment(item.id)} /><span><strong>{item.name}</strong><small>{item.plainDescription}</small></span></label> })}</div>}</Card></section><Card className="library-note"><Icon name="book" size={21} /><p>Structured plan import is the next data capability. Forge does not yet execute or invent workout plans.</p></Card><p className="privacy-note">Your profile, safety acknowledgement, settings, and equipment choices stay on this device.</p></div> }
function Stat({ label, value, note, icon }: { label: string; value: string; note: string; icon: IconName }) { return <Card className="stat-card"><div className="stat-icon"><Icon name={icon} size={19} /></div><p>{label}</p><h3>{value}</h3><span>{note}</span></Card> }
